name: build

on:
  push:
    branches:
    - source

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Read site version
      id: site-version
      run: |
        . ./.env
        echo "::set-output name=SITE_VERSION::${SITE_VERSION}"
    - name: Cache cargo-bin
      id: cache-cargo-bin
      uses: actions/cache@v1
      with:
        path: ~/.cargo/bin
        key: ${{ runner.os }}-cargo-bin-${{ hashFiles('.env') }}
    - name: Install site
      if: steps.cache-cargo-bin.outputs.cache-hit != 'true'
      run: cargo install --version ${{ steps.site-version.outputs.SITE_VERSION }} site
    - name: Build
      run: site build --root-dir . --config=config-release.toml --out-dir ./build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./build
